[package]
name = "clock"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
nalgebra = "0.33.2"

pollster = "0.4.0"
rand = "0.9.1"
rapier2d = { version = "0.26.0", features = ["simd-stable"] }
vello = "0.5.0"

winit = "0.30.11"
